# Exported from Render on 2024-12-31T16:37:10Z
services:
  - type: web
    name: 365API
    runtime: node
    repo: https://github.com/chedenis/365API
    plan: standard
    envVars:
      - key: DEV_CORS_ORIGINS
        sync: false
      - key: FRONTEND_PROD_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: WEB_SUCCESS_REDIRECT
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: PROD_CORS_ORIGINS
        sync: false
      - key: PORT
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MAPBOX_API_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AUTHORIZED_EMAILS
        sync: false
    region: oregon
    buildCommand: npm install
    startCommand: npm start
version: "1"
